### ISSUE TITLE
creating a room with a blank name Throws unhandled promise error. 

### ISSUE THREAD

**Issue by zork4cyber** [hub-up/smart-server#4]
`Client Input`

» /room
You have left Lobby and created
You are now the leader of

`Server Error`

(node:13325) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'to' of undefined
    at sendToRoom (/Users/alexwhite/Desktop/CodeFellows/401/projects/hub_up/smart-server/src/api/lib/send-to-room.js:13:10)
    at room (/Users/alexwhite/Desktop/CodeFellows/401/projects/hub_up/smart-server/src/api/command-handlers/room.js:38:7)
    at handleCommand (/Users/alexwhite/Desktop/CodeFellows/401/projects/hub_up/smart-server/src/api/event-handlers/handle-command.js:21:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:13325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CharmedSatyr** [comment]
No longer throws an error, but creates a room with no name. File another issue for an enhancement.
